version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  sonar:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
          name: Installing requirements
      - run:
          command: python -m unittest -v
          name: Running tests
  infrastructure-providing-and-deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd IAC &&
            terraform init
      - run:
          name: Terraform provide and deploy
          command: |
            cd IAC &&
            terraform apply -auto-approve -var="ecr_image_tag=${CIRCLE_SHA1}"

workflows:
  main:
    jobs:
#      - sonar
#      - test
      - aws-ecr/build-and-push-image:
          context: TerraformContext
          repo: "${TF_VAR_service_name}"
          tag: "${CIRCLE_SHA1}"
          create-repo: true
          aws-access-key-id: TF_VAR_aws_provider_key
          aws-secret-access-key: TF_VAR_aws_provider_secret
          account-url: TF_VAR_aws_ecr_account_url
#          requires:
#            - sonar
#            - test
          filters:
            branches:
              only:
                - master
                - qa
                - feature/Pilot
      - infrastructure-providing-and-deploy:
          context:
            - TerraformContext
            - KafkaVisualUploadContext
          requires:
            - aws-ecr/build-and-push-image

