
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2

jobs:
  infrastructure-providing-and-deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd init_sound_monitor_iac &&
            terraform init
      - run:
          name: Terraform provide and deploy
          command: |
            cd init_sound_monitor_iac &&
            terraform apply -auto-approve
workflows:
  main:
    jobs:
      - infrastructure-providing-and-deploy:
          context:
            - TerraformContext


