version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  infrastructure-providing-and-deploy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform init
          command: |
            cd IAC &&
            terraform init
      - run:
          name: Terraform provide and deploy
          command: |
            cd IAC &&
            terraform apply -auto-approve -var="ecr_image_tag=${CIRCLE_SHA1}"

workflows:
  main:
    jobs:
      - infrastructure-providing-and-deploy:
          context:
            - TerraformContextTest

